import { GetStaticPaths, GetStaticProps } from "next";
import { ParsedUrlQuery } from "querystring";
import ProductContainer from "@/components/Product/Product";
import ProductMContainer from "@/components/Product/ProductM";
import { ProductType } from "@/type/type";
import Head from "next/head";
type Props = {
  product: ProductType;
  status: number;
};
export default function Product({ product, status }: Props) {
  return (
    <>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductContainer product={product} status={status} />
      <ProductMContainer product={product} />
    </>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  const productIds = ["M21210"];
  const paths = productIds.map((item: string) => ({
    params: {
      id: item,
    },
  }));

  console.log(paths);
  return {
    paths,
    fallback: false,
  };
};

interface Params extends ParsedUrlQuery {
  id: string;
}

export const getStaticProps: GetStaticProps<Props, Params> = async (
  context
) => {
  const { id } = context.params!;
  console.log(id);
  const res = await fetch(process.env.BaseUrl + "/product/detail/", {
    method: "post",
    body: JSON.stringify({
      productId: id,
    }),
    headers: {
      "Content-Type": "application/json",
    },
  });
  const res_json = await res.json();
  const data = res_json.data;
  console.log(data);
  const product = {
    productId: data.productId,
    name: data.name,
    details: [
      { content: "26 x 20 x 12 厘米", lists: ["羊皮革", "肩带：可拆卸"] },
    ],
    images: data.images.map((item: string) => process.env.BaseUrl + item),
    description:
      "本款 Coussin 小号手袋为蓬软羊皮革压印经典 Monogram 图案，与粗链条等金属件共同释放耀目莹泽。系上宽幅织物肩带，解锁肩背和斜挎方式，令简约造型释放潮流格调,解锁肩背和斜挎方式，令简约造型释放潮流格调",
    tags: [
      { title: "Sustainability", description: "" },
      { title: "Product Care", description: "" },
    ],
    services: [
      {
        title: "支付方式",
        icon: "",
        desc: "Credit card, debit card or bank transfer",
      },
      {
        title: "配送服务",
        icon: "",
        desc: "Complimentary Delivery or Collect-in-Store",
      },
      {
        title: "退换货服务",
        icon: "",
        desc: "Complimentary, in store and online",
      },
    ],
    price: data.price,
    detail: data.detail,
    status: data.status,
    color: data.color,
    recommand: [
      {
        images: [
          "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
        ],
        name: "COUSSIN 中号",
        price: 29100,
        color: "green",
      },
      {
        images: [
          "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
          "https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80",
        ],
        name: "COUSSIN 中号2",
        price: 29100,
        color: "green",
      },
    ],
  };

  return {
    props: {
      product,
      status: data.status,
    },
  };
};
