import { GetServerSideProps} from "next";
import { ParsedUrlQuery } from "querystring";
import ProductContainer from "@/components/Product/Product";
import ProductMContainer from "@/components/Product/ProductM";
import { ProductType } from "@/type/type";
import Head from "next/head";
import { getProductDetail } from "@/fetchMethod/products";
type Props = {
  product: ProductType;
  status: number;
};
export default function Product({ product, status }: Props) {
  return (
    <>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductContainer product={product} status={status} />
      <ProductMContainer product={product} />
    </>
  );
}

interface Params extends ParsedUrlQuery {
  id: string;
}

export const getServerSideProps: GetServerSideProps<Props, Params> = async (
  context
) => {
  const { productId }  = context.query;
  console.log(productId);
  
  const prop = await getProductDetail(productId as string)
  
  return {
    props: {
      ...prop
    },
  };
};
