import {
  Box,
  Flex,
  UnstyledButton,
  Image,
  Text,
  SimpleGrid,
  createStyles,
} from "@mantine/core";
import { gray_layout } from "@/type/const";
import { useState } from "react";
import Head from "next/head";
import Card from "@/components/profile/Card";
import { backgroundColor } from "@/type/const";
import { useAppSelector } from "@/store/hooks";
import { selectUserInfo } from "@/features/roleFeature/roleFeature";

const title = ["Overview", "My Profile", "My Orders", "My Wishlist"];
const useStyles = createStyles((theme) => ({}));
function acount() {
  const [activeIndex, setActiveIndex] = useState(0);
  const info = useAppSelector(selectUserInfo);

  const { theme } = useStyles();
  return (
    <>
      <Head>
        <title>My Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          position: "relative",
          backgroundColor:
            theme.colorScheme === "light" ? backgroundColor : "black",
        }}
      >
        <Flex
          justify={"flex-end"}
          sx={{
            position: "sticky",
            top: 0,
            zIndex: 10,
            backgroundColor: theme.colorScheme === "light" ? "white" : "black",
          }}
        >
          {title.map((item, index) => (
            <UnstyledButton
              key={item}
              sx={{
                padding: "1.5rem 2rem",
                borderLeft: `1px solid ${gray_layout}`,
                borderBottom:
                  activeIndex === index ? "0.3rem solid black" : "none",
              }}
              onClick = {()=>setActiveIndex(index)}
            >
              {item}
            </UnstyledButton>
          ))}
        </Flex>
        <Box sx={{ position: "relative" }}>
          <Image
            src={"/profile.webp"}
            width={"100%"}
            height={"20rem"}
            fit={"cover"}
          />
          <Box
            sx={{
              position: "absolute",
              bottom: "-3rem",
              left: "calc(50% - 3rem)",
            }}
          >
            <Box
              sx={{
                borderRadius: "50%",
                width: "6rem",
                height: "6rem",
                backgroundColor:
                  theme.colorScheme === "light" ? "white" : "black",
                border: `1px solid ${gray_layout}`,
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              {info.name ? info.name[0] : "G"}
            </Box>
          </Box>
        </Box>
        <Box sx={{ textAlign: "center", marginTop: "5rem" }}>
          <Text fw={600} fz="lg">
            {info.name ? info.name : "Guest"}
          </Text>
        </Box>
        <SimpleGrid
          cols={2}
          sx={{ margin: "3rem auto", width: "80%" }}
          spacing="lg"
        >
          <Card title="MY PROFILE">
            <Box>Phone Number</Box>
          </Card>
          <Card title="MY ORDERS">
            <Box>Phone Number</Box>
          </Card>
          <Card title="MY WISHLIST">
            <Box>Phone Number</Box>
          </Card>
        </SimpleGrid>
      </Box>
    </>
  );
}

export default acount;
