import Head from "next/head";
import { Box, Select, Text, Group, Title, SimpleGrid } from "@mantine/core";
import { useStyles } from "@/styles/wishlist";
import Product from "@/components/ProductList/Product";
import { selectWishList } from "@/features/roleFeature/roleFeature";
import { useAppSelector, useAppDispatch } from "@/store/hooks";
import { GetServerSideProps } from "next";
import { SimpleProduct } from "@/type/type";
import { getWishlist } from "@/fetchMethod/wishlist";
import { useEffect, useState } from "react";

const data = [
  { value: "react", label: "React" },
  { value: "ng", label: "Angular" },
  { value: "svelte", label: "Svelte" },
  { value: "vue", label: "Vue" },
];
export default function WishList() {
  const { classes } = useStyles();
  const [wishlist, setWishlist] = useState<SimpleProduct[]>([]);
  // const wishlist = useAppSelector(selectWishList);
  const dispatch = useAppDispatch();
  useEffect(() => {
    getWishlist(dispatch).then((w) => {
      console.log(w);

      setWishlist(
        w.map((item: SimpleProduct) => ({
          ...item,
          images: item.images.map((img: string) => process.env.BaseUrl + img),
        }))
      );
    });
  }, []);
  return (
    <>
      <Head>
        <title>Wishlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={classes.container}>
        <Group>
          <Title order={2} fw={500}>{`${wishlist.length}     items`}</Title>
          <Group sx={{ marginLeft: "auto" }}>
            <Text>Sort by</Text>
            <Select data={data} placeholder="Pick one" />
          </Group>
        </Group>
        <SimpleGrid
          cols={4}
          breakpoints={[
            { maxWidth: "62rem", cols: 3 },
            { maxWidth: "48rem", cols: 2 },
            { maxWidth: "36rem", cols: 1 },
          ]}
          sx={{ marginTop: "1rem" }}
        >
          {wishlist?.map((item) => (
            <Product product={{ ...item }} key={item.name} />
          ))}
        </SimpleGrid>
      </Box>
    </>
  );
}
