import Head from "next/head";
import { Box } from "@mantine/core";
export default function WishList() {
  return (
    <>
      <Head>
        <title>Wishlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>my wishlist</Box>
    </>
  );
}
